spring:
  application:
    name: api
  datasource:
    name: skytech
    url: jdbc:mysql://rm-j6c4h5730u6ivt82xmo.mysql.rds.aliyuncs.com:3306/skytech?characterEncoding=utf-8
    username: skytech
    password: 1957Forget
  # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 47.244.99.59
    port: 6379
    password: 1957Forget

mybatis:
  mapperLocations: classpath*:com/skytech/api/mapper/**/*.xml
  typeAliasesPackage: com.skytech.api.model

server:
  port: 9091
  servlet:
    context-path: /api

logging:
  level:
    ROOT: INFO
    com.skytech.api.mapper : debug
  path:
  file: logs/api.log